# `Machine Learning ZoomCamp`
## `HW1_Chapter 1`

### Aileah Gotladera
-----------------------------------

In [2]:
# Import
import numpy as np
import pandas as pd

### `Q1`
.Checking pandas version;

In [3]:
pd.__version__

'1.5.3'

#### Getting the data
Use the California Housing Prices Dataset.

In [11]:
data = pd.read_csv('C:/Users/arqui/Documents/ch1_hw1data.csv')
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

### `Q2`
How many clumns are in the dataset?

In [17]:
print(list(data.columns), '\n')
print(len(data.columns))

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity'] 

10


### `Q3`
Which columns in the dataset have missing values?

In [25]:
# Checking number of null values of all columns
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [26]:
# Check which column has null values
data.columns[data.isnull().any()].tolist()

['total_bedrooms']

### `Q4`
How many unique values does the ocean_proximity column have?

In [28]:
ocean_proxi_unique = data.ocean_proximity.unique()
print(len(ocean_proxi_unique))

5


### `Q5`
What's the average value of the median_house_value for the houses located near the bay?

In [33]:
ave = data.loc[data['ocean_proximity']== 'NEAR BAY', 'median_house_value'].mean()
print(round(ave, 0))

259212.0


### `Q6`
1. Calculate the average of `total_bedrooms` column in the dataset

In [36]:
ave_bedrooms = data['total_bedrooms'].mean()
ave_bedrooms

537.8705525375618

2. Use the fillna method to fill the NA values in total_bedrooms with the mean value from the previous step.

In [37]:
data['total_bedrooms'].fillna(ave_bedrooms, inplace=True)

3. Calculate the average of `total_bedrooms` again. Has it changed?

In [38]:
data['total_bedrooms'].mean()

537.8705525375617

### `Q7`
1. Select all the options located on islands

In [72]:
all_islands = data[data['ocean_proximity'] =='ISLAND']
all_islands.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`

In [73]:
filtered = all_islands[['housing_median_age', 'total_rooms', 'total_bedrooms']]
filtered.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

3. Get the underlying NumPy Array. Let's call it `x`

In [74]:
x = filtered.values
x

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

4. Compute matrix-matrix multiplication between the transpose of X and `X`.<br> 
Let's call the result `XTX`.

In [75]:
# Transpose of 'x'
x_transpose = x.T

# Compute the matrix-matrix multiplication between 'x_transpose' and 'x'
xTx = x @ x_transpose
print(xTx)

[[3077795. 4260640. 3830881. 1807248. 1311577.]
 [4260640. 5916866. 5322889. 2508292. 1817026.]
 [3830881. 5322889. 4788977. 2256364. 1634008.]
 [1807248. 2508292. 2256364. 1064416.  771140.]
 [1311577. 1817026. 1634008.  771140.  559293.]]


5. Compute the inverse of `xTx`

In [76]:
# Inverse of xTx
inverse_xTx = np.linalg.inv(xTx)
print(inverse_xTx)

[[ 4.50889141e+08 -2.65092831e+09  2.66146909e+09 -5.26157398e+08
   5.04760603e+08]
 [ 2.60444475e+11 -8.57212683e+10 -2.18771394e+10  5.28097320e+11
  -9.96480838e+11]
 [-2.81125831e+11  9.36268739e+10  2.24292933e+10 -5.69400064e+11
   1.07463035e+12]
 [ 1.50907516e+11 -5.52172767e+10 -6.69134384e+09  3.02798151e+11
  -5.72439948e+11]
 [-2.33928769e+11  8.73028262e+10  8.53028316e+09 -4.68398445e+11
   8.85843939e+11]]


6. Create an array `y` with values: `[950, 1300, 800, 1000, 1300]`

In [81]:
y = np.array([950, 1300, 800, 1000, 1300])
y_reshaped = y.reshape(-1,1)
y

array([ 950, 1300,  800, 1000, 1300])

7. Multiply inverse of `xTx` with the transpose of `x`. Then multiply the result by `y`.<br>
Call this `w`

In [93]:
# Matrices shapes
newline= '\n'
print(f"Matrices' shapes:{newline}{inverse_xTx.shape}")
print(x_transpose.shape)
print(y_reshaped.shape, '\n')
result = x_transpose @ inverse_xTx 
w = result @ y_reshaped
w

Matrices' shapes:
(5, 5)
(3, 5)
(5, 1) 



array([[  15.87753296],
       [-141.87927246],
       [ -28.7399292 ]])

8. Whats' the value of the last element of `w`?

In [89]:
w[-1]

array([-28.7399292])

-------------------------------------